name: Miles 2 code
description: Blogging about stuffs
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Rahul"

# Disqus config
disqus-shortname: ""
